name: "Test: Python"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:

  test:
    name: "test backend"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r backend/requirements.txt
      - run: pytest backend/tests
